leftnav:
- identifier: 2194fd7c-6438-3372-4400-e0ff6cc66e2c
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: external-e19f40bfb341450b8a737735ed926684
  name: 2.009 PRODUCT ENGINEERING PROCESS
  url: https://web.mit.edu/2.009/www/index.html
  weight: 1000
- identifier: external-abeb6ee689f146f4b672ea3e8efcd655
  name: 2.S009 EXPLORATIONS IN PRODUCT DESIGN
  url: https://2s009.com/
  weight: 1010
